# My Shell

# author: Internet's own boy

# Operating Systems Internal - Assignment 1
# Description: a makefile to compile source and header files into myshell

myshell: myshell.c
	gcc -W -Wall -std=gnu99 -pedantic myshell.c myshell.h -o myshell
clean:
	rm -rf *.o
	rm -rf myshell 
